name: ots-stamp
on:
  push:
    paths:
      - "docs/index.html"
      - "docs/**/*.html"
      - "index.html"
      - "asi-letter-*.md"
      - "letters/**/*.md"
  workflow_dispatch:
    inputs:
      files:
        description: "Space-separated list of files to stamp"
        required: false
        default: "docs/index.html"

permissions:
  contents: write

jobs:
  stamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <-- ensure the BEFORE commit exists

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install OpenTimestamps client
        run: pip install --upgrade opentimestamps-client

      - name: Ensure helper script is executable
        run: chmod +x scripts/ots-stamp-and-inject.sh

      - name: Decide which files to stamp
        id: files
        shell: bash
        run: |
          set -euo pipefail

          # 1) Manual input wins (workflow_dispatch)
          if [[ -n "${{ github.event.inputs.files || '' }}" ]]; then
            echo "changed=${{ github.event.inputs.files }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # 2) Candidate globs (keep in one place)
          CANDS=( "docs/index.html" "docs/**/*.html" "index.html" "asi-letter-*.md" "letters/**/*.md" )

          # 3) Try to diff against event.before if the object exists
          BEFORE="${{ github.event.before }}"
          CHANGED=""
          if [[ -n "$BEFORE" ]] && git cat-file -e "$BEFORE^{commit}" 2>/dev/null; then
            CHANGED=$(git diff --name-only "$BEFORE" "${{ github.sha }}" -- "${CANDS[@]}" || true)
          else
            # 4) Fallback: diff HEAD^..HEAD if possible
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              CHANGED=$(git diff --name-only HEAD^ HEAD -- "${CANDS[@]}" || true)
            fi
          fi

          # 5) Last resort: stamp docs/index.html so the job always produces output
          if [[ -z "$CHANGED" ]]; then
            CHANGED="docs/index.html"
          fi

          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
          printf "Changed files:\n%s\n" "$CHANGED"

      - name: Stamp each file
        if: steps.files.outputs.changed != ''
        shell: bash
        run: |
          set -euo pipefail
          for f in ${{ steps.files.outputs.changed }}; do
            if [[ -f "$f" ]]; then
              echo "Stamping $f"
              ./scripts/ots-stamp-and-inject.sh "$f"
            else
              echo "WARN: $f not found; skipping"
            fi
          done

      - name: Commit proofs & optional injection changes
        if: steps.files.outputs.changed != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ots): add/update proofs and appendix [skip ci]"
          file_pattern: |
            proofs/**
            index.html
            docs/index.html
            asi-letter-*.md
            letters/**/*.md
