name: ots-upgrade-scheduler

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  workflows: write

jobs:
  maybe-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Determine whether an update is still pending
        id: decision
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          REF: ${{ github.ref }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          REPOSITORY: ${{ github.repository }}
        shell: bash
        run: |
          set -euo pipefail

          python .github/scripts/check_letter_finalization.py \
            --event-name "$EVENT_NAME" \
            --repository "$REPOSITORY" \
            --ref-name "$REF_NAME" \
            --ref "$REF" \
            --default-branch "$DEFAULT_BRANCH" \
            --force false \
            --github-output "${GITHUB_OUTPUT:-}"

      - name: Dispatch ots-upgrade workflow
        if: steps.decision.outputs.should_run == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const rawRef = context.ref || `refs/heads/${context.payload?.repository?.default_branch || 'main'}`;
            const branch = rawRef.replace(/^refs\/heads\//, '');
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ots-upgrade.yml',
              ref: branch,
              inputs: { force: 'false' },
            });
