name: ots-upgrade
on:
  schedule:
    - cron: "23 * * * *"
  workflow_dispatch: {}

concurrency:
  group: letter-artifacts-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  upgrade-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenTimestamps client + alt verifier
        run: |
          python -m pip install --upgrade opentimestamps-client
          wget -q https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          /usr/local/go/bin/go install github.com/fiatjaf/ots@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: "Update footer status line from newest /letter/*.asc (fallback: docs/letter.md.asc)"
        shell: bash
        run: |
          set -euo pipefail
          HTML="docs/index.html"
          [[ -f "$HTML" ]] || { echo "Missing $HTML" >&2; exit 1; }

          TARGET=""
          if ls letter/*.asc 1>/dev/null 2>&1; then
            TARGET="$(ls -t letter/*.asc | head -n1)"
          elif [[ -f docs/letter.md.asc ]]; then
            TARGET="docs/letter.md.asc"
          fi

          HEIGHT=""
          if [[ -n "$TARGET" ]]; then
            echo "Using TARGET='$TARGET'"
            if [ ! -f "${TARGET}.ots" ]; then
              echo "No .ots present; stamping"
              ots stamp "$TARGET"
            else
              echo "Found ${TARGET}.ots; skipping stamp."
            fi
            # Always attempt to upgrade; ignore 'nothing to do' errors
            ots upgrade "${TARGET}.ots" || true
            if [[ -f "${TARGET}.ots" ]]; then
              git add "${TARGET}.ots"
            fi
            cp "${TARGET}.ots" /tmp/proof.ots
            ots upgrade /tmp/proof.ots || true

            if PY_OUT="$(python .github/scripts/extract_block_height.py /tmp/proof.ots)"; then
              HEIGHT="${PY_OUT//$'\n'/}"
              HEIGHT="${HEIGHT//$'\r'/}"
            fi

            if [[ -z "$HEIGHT" ]]; then
              set +e
              OUT="$(ots verify /tmp/proof.ots 2>&1)"
              ALT="$("$HOME/go/bin/ots" verify /tmp/proof.ots 2>&1)"
              INFO="$(ots info /tmp/proof.ots 2>&1)"
              OUT="$OUT"$'\n'"$ALT"$'\n'"$INFO"
              set -e
              HEIGHT="$(echo "$OUT" |
                grep -Eo 'block[[:space:]]*#?[0-9]+|blockheight[[:space:]]*#?[0-9]+|BitcoinBlockHeaderAttestation\([0-9]+\)' |
                grep -Eo '[0-9]+' |
                tail -n1 || true)"
            fi
          fi

          awk -v height="$HEIGHT" '
            BEGIN{RS=""; ORS=""}
            {
              if (length(height) > 0) {
                gsub(/<p id="ots-line">.*<\/p>/,
                     "<p id=\"ots-line\">Bitcoin block <strong>" height "</strong> attests the letter existed prior to that block.</p>", $0);
              } else {
                gsub(/<p id="ots-line">.*<\/p>/,
                     "<p id=\"ots-line\">Bitcoin anchoring pending. Proof will update automatically.</p>", $0);
              }
              printf "%s\n", $0
            }' "$HTML" > "$HTML.tmp"
          mv "$HTML.tmp" "$HTML"

      - name: Rebase onto latest ${{ github.ref_name }} before committing
        shell: bash
        run: |
          set -euo pipefail
          branch="${GITHUB_REF##*/}"
          git fetch origin "$branch"
          git pull --rebase --autostash origin "$branch"

      - name: Wait for GitHub Pages to be idle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/wait_for_pages_idle.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ots): upgrade proof + refresh status [ots-upgrade-auto]"
          file_pattern: docs/index.html

