name: ots-verify-upgrade
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  verify-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip opentimestamps-client
          echo "$(python -c 'import sysconfig; print(sysconfig.get_path("scripts"))')" >> "$GITHUB_PATH"

      - name: Show OTS info/verify (before)
        run: |
          set -e
          echo "::group::info"
          ots info letter/ASI-Letter-v2025.09.14.md.asc.ots || true
          echo "::endgroup::"
          echo "::group::verify (before)"
          ots verify letter/ASI-Letter-v2025.09.14.md.asc.ots || true
          echo "::endgroup::"

      - name: Upgrade proof
        run: |
          ots upgrade letter/ASI-Letter-v2025.09.14.md.asc.ots || true

      - name: Show verify (after)
        run: |
          echo "::group::verify (after)"
          ots verify letter/ASI-Letter-v2025.09.14.md.asc.ots || true
          echo "::endgroup::"

      - name: Commit upgraded proof if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ots): upgrade ASI-Letter-v2025.09.14 proof"
          file_pattern: "letter/ASI-Letter-v2025.09.14.md.asc.ots"
