name: ots-verify-upgrade
on:
  workflow_dispatch:

concurrency:
  group: letter-artifacts-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  verify-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip opentimestamps-client
          echo "$(python -c 'import sysconfig; print(sysconfig.get_path("scripts"))')" >> "$GITHUB_PATH"

      - name: Determine latest OTS proof
        id: latest-ots
        run: |
          set -eo pipefail
          python scripts/find_latest_ots.py letter >> "$GITHUB_OUTPUT"

      - name: Show OTS info/verify (before)
        run: |
          set -e
          echo "::group::info"
          ots info "${{ steps.latest-ots.outputs.latest }}" || true
          echo "::endgroup::"
          echo "::group::verify (before)"
          ots verify "${{ steps.latest-ots.outputs.latest }}" || true
          echo "::endgroup::"

      - name: Upgrade proof
        run: |
          ots upgrade "${{ steps.latest-ots.outputs.latest }}" || true

      - name: Show verify (after)
        run: |
          echo "::group::verify (after)"
          ots verify "${{ steps.latest-ots.outputs.latest }}" || true
          echo "::endgroup::"

      - name: Commit upgraded proof if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ots): upgrade ${{ steps.latest-ots.outputs.version }} proof"
          file_pattern: "letter/${{ steps.latest-ots.outputs.basename }}"
