name: ots-upgrade
on:
  schedule:
    - cron: "23 * * * *"   # hourly on default branch
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  upgrade-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenTimestamps client + alt verifier
        run: |
          python -m pip install --upgrade opentimestamps-client
          wget -q https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          /usr/local/go/bin/go install github.com/fiatjaf/ots@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Compute current status and update footer line
        shell: bash
        run: |
          set -euo pipefail
          HTML="docs/index.html"
          [[ -f "$HTML" ]] || { echo "Missing $HTML" >&2; exit 1; }

          HEIGHT=""
          if [[ -f docs/letter.md.asc ]]; then
            # Create a transient proof, upgrade it, and read block height
            ots stamp docs/letter.md.asc
            mv docs/letter.md.asc.ots /tmp/proof.ots
            ots upgrade /tmp/proof.ots || true

            set +e
            OUT="$(ots verify /tmp/proof.ots 2>&1)"
            ALT="$("$HOME/go/bin/ots" verify /tmp/proof.ots 2>&1)"
            OUT="$OUT"$'\n'"$ALT"
            set -e
            HEIGHT="$(echo "$OUT" | grep -Eo 'block[[:space:]]*\[?[0-9]+\]?' | grep -Eo '[0-9]+' | tail -n1 || true)"
          fi

          awk -v height="$HEIGHT" '
            BEGIN{RS=""; ORS=""}
            {
              if (length(height) > 0) {
                gsub(/<p id="ots-line">.*<\/p>/,
                     "<p id=\"ots-line\">Bitcoin block <strong>" height "</strong> attests the letter existed prior to that block.</p>", $0);
              } else {
                gsub(/<p id="ots-line">.*<\/p>/,
                     "<p id=\"ots-line\">Bitcoin anchoring pending. Proof will update automatically.</p>", $0);
              }
              print
            }' "$HTML" > "$HTML.tmp"
          mv "$HTML.tmp" "$HTML"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ots): update footer status line (pending → block height) [skip ci]"
          file_pattern: docs/index.html
