name: Verify OpenPGP clear-signed releases

on:
  push:
    paths:
      - "releases/**/*.asc"
      - "scripts/asi-public.asc"
      - "scripts/verify-clearsign.sh"
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GnuPG
        run: sudo apt-get update && sudo apt-get install -y gnupg

      # This script imports scripts/asi-public.asc and DERIVES the fingerprint; no hard-coding.
      # If you want to pin later, add:
      #   env:
      #     EXPECTED_FPR: "<your 40-hex fingerprint>"
      - name: Verify fingerprints and signatures
        run: bash scripts/verify-clearsign.sh
